TD-Liste-main	:	TD-Liste.o TD-Liste-Main.o
	g++ -o TD-Liste TD-Liste.o TD-Liste-Main.o
TD-Liste-Main.o : TD-Liste-Main.cpp
	g++ -c TD-Liste-Main.cpp
TD-Liste.o	:	TD-Liste.cpp TD-Liste.h
	g++ -c TD-Liste.cpp
